kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/webhookrelay/relay-go

steps:
- name: build
  image: golang:1.14
  environment:
    GO111MODULE: off
  commands:
    - make install

- name: test
  image: golang:1.14
  environment:
    GO111MODULE: off
  commands:
    - make test-pretty 

- name: e2e-test
  image: golang:1.14
  environment:
    GO111MODULE: off
    BUCKETS:
      from_secret: buckets
    INPUT_URL:
      from_secret: input_url
    RELAY_KEY:
      from_secret: relay_key
    RELAY_SECRET:
      from_secret: relay_secret    
  commands:
    - make install
    - make e2e

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_url
    channel: general
    username: drone
    icon_url: https://i.pinimg.com/originals/51/29/a4/5129a48ddad9e8408d2757dd10eb836f.jpg
